# -*- coding: utf-8 -*-
"""6_Despliegue-CarRiskStreamLit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1niQkyOBXNFH-8SHi6waNxkeIzC-OMNRg

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el modelo
import pickle
filename = 'modelo-cla.pkl'
modelo_knn, min_max_scaler, variables, labelencoder = pickle.load(open(filename, 'rb'))

#Cargamos los datos futuros
#data = pd.read_csv("carRisk - futuro.csv")
#data.head()


#Interfaz Gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción CarRisk')

edad = st.slider('Edad', min_value=data['edad'].min(), max_value=data['edad'].max(), value=int(data['edad'].mean()), step=1)
tipoCarro = ['combi', 'sport', 'family', 'minivan'] 

#Dataframe
datos = [[edad, tipoCarro]]
data = pd.DataFrame(datos, columns=['edad', 'tipoCarro']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación
data_preparada=data.copy()

#Preparamos los datos futuros: dummies
data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['tipoCarro'], dtype=int, drop_first=False) #Siempre drop_first=False en el despliegue
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red
#En los despliegues no se llama fit
#data_preparada[['Edad']]= min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""#**Predicciones**"""

#Ahora que están las variables completas se puede hacer la predicción
Y_tree = modelo_knn.predict(data_preparada)
Y_tree

print(labelencoder.inverse_transform(Y_tree))

#Predicciones finales
data

#Cargar datos futuros
#data = pd.read_csv("carRisk - futuro.csv")
#data.head()
